<?php

/**
 * @file
 *
 * Resource (API) definitions.
 */

/**
 * Implements hook_services_resources().
 */
function turntable_master_services_resources() {
  return array(
    'node-shared' => array(
      'create' => array(
        'help' => t('Saves a (possibly new) shared node'),
        'file' => array(
          'file' => 'service.php',
          'module' => 'turntable_master'
        ),
        'callback' => 'turntable_master_save_shared_node',
        'args' => array(
          array(
            'name' => 'data',
            'type' => 'struct',
            'description' => 'The shared node object',
            'source' => 'data',
            'optional' => FALSE
          )
        ),
        'access callback' => 'turntable_master_access',
        'access arguments' => array(
          'save'
        ),
        'access arguments append' => TRUE
      ),
      'index' => array(
        'help' => t('Retrieves a list of shared nodes'),
        'file' => array(
          'file' => 'service.php',
          'module' => 'turntable_master'
        ),
        'callback' => 'turntable_master_find_shared_node',
        'args' => array(
          array(
            'name' => 'query',
            'type' => 'string',
            'description' => 'Search query',
            'source' => array(
              'param' => 'query'
            ),
            'optional' => FALSE
          )
        ),
        'access callback' => 'turntable_master_access',
        'access arguments' => array(
          'read'
        ),
        'access arguments append' => TRUE
      )
    )
  );
}

/**
 * Endpoint definition.
 */
function turntable_master_default_services_endpoint() {
  $endpoints = array();

  $endpoint = new stdClass();
  $endpoint->disabled = FALSE; // Edit this to TRUE to make a default endpoint disabled initially
  $endpoint->api_version = 3;
  $endpoint->name = 'turntable_master_v1';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'api/turntable/v1';
  $endpoint->authentication = array();

  // server settings
  $endpoint->server_settings = array(
    'formatters' => array(
      'json' => TRUE,
      'bencode' => FALSE,
      'jsonp' => FALSE,
      'php' => FALSE,
      'xml' => FALSE
    ),
    'parsers' => array(
      'application/json' => TRUE,
      'application/vnd.php.serialized' => FALSE,
      'application/x-www-form-urlencoded' => FALSE,
      'application/xml' => FALSE,
      'multipart/form-data' => FALSE,
      'text/xml' => FALSE
    )
  );

  // resource definitions
  $endpoint->resources = array(
    'node-shared' => array(
      'operations' => array(
        'create' => array(
          'enabled' => '1'
        ),
        'read' => array(
          'enabled' => '1'
        )
      )
    ),
    // this is only a workaround: creating node-shared-search doesn't really
    // make sense but we need to be able to send data with every request
    'node-shared-search' => array(
      'operations' => array(
        'create' => array(
          'enabled' => '1'
        )
      )
    )
  );

  // debug mode enabled
  $endpoint->debug = 1;

  $endpoints[] = $endpoint;

  return $endpoints;
}

function turntable_master_access($op, $args) {
  // grant access without authentication/authorization
  // access for everyone
  // FIXME big security flaw
  return TRUE;
}

